Repository open-cluster-management-io/lab, pull requests merged in 2025-07, with the labels that each got.

#4 chore: update README with current and upcoming projects
  README.md
Labels: approved, lgtm

#9 ci: fix monorepo release workflows
  .github/actions/prepare-release-env/action.yml
  .github/workflows/chart-upload.yml
  .github/workflows/release.yml
  .github/workflows/releaseimage.yml
  README.md
Labels: approved, lgtm

#12 🐛 use consistent repo for all fleetconfig-controller images, move variant into tag
  fleetconfig-controller/Makefile
Labels: fleetconfig-controller

#15 🐛 pass component to `download-chart` action in OCM `helm-charts` repo
  .github/workflows/chart-upload.yml
Labels: approved, lgtm

#7 chore: update README and add a new root OWNER
  OWNERS
  README.md
Labels: approved, lgtm

#8 chore: add OWNERS file to fleetconfig-controller
  fleetconfig-controller/OWNERS
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#18 ✨ configurable `issuerRef` for fleetconfig-controller certs; tidy lingering multicluster refs
  .github/workflows/test.yml
  fleetconfig-controller/OWNERS
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/templates/admission-webhooks/serving-cert.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/clusterissuer.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/test/e2e/fleetconfig.go
Labels: lgtm

#19 🌱 add `TylerGillson` to root OWNERS
  OWNERS
Labels: approved, lgtm

#21 ✨ separate create topology resources flag from create FleetConfig flag
  fleetconfig-controller/api/v1alpha1/fleetconfig_webhook.go
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/templates/ocm/topology-resources.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/internal/controller/fleetconfig_controller.go
  fleetconfig-controller/internal/controller/fleetconfig_controller_test.go
  fleetconfig-controller/internal/controller/hub.go
  fleetconfig-controller/internal/controller/spoke.go
  fleetconfig-controller/test/e2e/fleetconfig.go
  fleetconfig-controller/test/e2e/helper.go
Labels: approved, lgtm, fleetconfig-controller

#23 🐛 correctly handle GKE-Ingress provider in `controller.image` helm func; correctly prefer global kubernetes provider
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/templates/_helpers.tpl
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
Labels: approved, lgtm

#25 🌱 parameterize all base images in fleetconfig-controller Dockerfiles; bump to v0.0.5
  fleetconfig-controller/build/Dockerfile.base
  fleetconfig-controller/build/Dockerfile.devspace
  fleetconfig-controller/build/Dockerfile.eks
  fleetconfig-controller/build/Dockerfile.gke
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
Labels: approved, lgtm, fleetconfig-controller

#26 🌱 update fleetconfig API to support configuring add-ons
  fleetconfig-controller/api/v1alpha1/fleetconfig_types.go
  fleetconfig-controller/api/v1alpha1/zz_generated.deepcopy.go
  fleetconfig-controller/charts/fleetconfig-controller/crds/fleetconfig.open-cluster-management.io-crds.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/fleetconfig.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/ocm/add-ons.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/config/crd/bases/fleetconfig.open-cluster-management.io_fleetconfigs.yaml
Labels: approved, lgtm

#28 ✨ implement addon create and delete reconcile on the hub
  fleetconfig-controller/api/v1alpha1/constants.go
  fleetconfig-controller/api/v1alpha1/fleetconfig_webhook.go
  fleetconfig-controller/api/v1alpha1/validation.go
  fleetconfig-controller/api/v1alpha1/zz_generated.deepcopy.go
  fleetconfig-controller/charts/fleetconfig-controller/templates/ocm/add-ons.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/rbac/manager-rbac.yaml
  fleetconfig-controller/go.mod
  fleetconfig-controller/internal/controller/addon.go
  fleetconfig-controller/internal/controller/hub.go
  fleetconfig-controller/pkg/common/common.go
  fleetconfig-controller/vendor/modules.txt
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/0000_00_addon.open-cluster-management.io_clustermanagementaddons.crd.yaml
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/0000_02_addon.open-cluster-management.io_addondeploymentconfigs.crd.yaml
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/doc.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/register.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/types_addondeploymentconfig.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/types_addontemplate.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/types_clustermanagementaddon.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/types_managedclusteraddon.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/zz_generated.deepcopy.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/addon/v1alpha1/zz_generated.swagger_doc_generated.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/clientset.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/scheme/doc.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/scheme/register.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/addon_client.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/addondeploymentconfig.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/addontemplate.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/clustermanagementaddon.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/doc.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/generated_expansion.go
  fleetconfig-controller/vendor/open-cluster-management.io/api/client/addon/clientset/versioned/typed/addon/v1alpha1/managedclusteraddon.go
Labels: approved, lgtm, fleetconfig-controller

#32 ✨ global and per-spoke klusterlet annotations; bump to v0.0.6
  fleetconfig-controller/api/v1alpha1/fleetconfig_types.go
  fleetconfig-controller/api/v1alpha1/zz_generated.deepcopy.go
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/crds/fleetconfig.open-cluster-management.io-crds.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/fleetconfig.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/config/crd/bases/fleetconfig.open-cluster-management.io_fleetconfigs.yaml
  fleetconfig-controller/internal/controller/fleetconfig_controller.go
  fleetconfig-controller/internal/controller/spoke.go
  fleetconfig-controller/test/data/fleetconfig-values.yaml
  fleetconfig-controller/test/e2e/fleetconfig.go
  fleetconfig-controller/test/e2e/helper.go
Labels: approved, lgtm, fleetconfig-controller

#34 🐛 ignore hub apiserver override when forcing internal endpoint lookup
  .github/repositories.json
  fleetconfig-controller/Makefile
  fleetconfig-controller/api/v1alpha1/fleetconfig_types.go
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/crds/fleetconfig.open-cluster-management.io-crds.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/fleetconfig.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/config/crd/bases/fleetconfig.open-cluster-management.io_fleetconfigs.yaml
  fleetconfig-controller/internal/controller/addon.go
  fleetconfig-controller/internal/controller/hub.go
  fleetconfig-controller/internal/controller/spoke.go
  fleetconfig-controller/internal/exec/exec.go
  fleetconfig-controller/internal/exec/exec_test.go
  fleetconfig-controller/test/data/fleetconfig-values.yaml
Labels: approved

#36 chore: bump fleetconfig-controller to v0.0.8
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
Labels: approved, lgtm, fleetconfig-controller

#33 ✨ implement addon enable/disable flow
  fleetconfig-controller/api/v1alpha1/constants.go
  fleetconfig-controller/api/v1alpha1/fleetconfig_types.go
  fleetconfig-controller/api/v1alpha1/fleetconfig_types_test.go
  fleetconfig-controller/api/v1alpha1/fleetconfig_webhook.go
  fleetconfig-controller/api/v1alpha1/validation.go
  fleetconfig-controller/api/v1alpha1/zz_generated.deepcopy.go
  fleetconfig-controller/charts/fleetconfig-controller/crds/fleetconfig.open-cluster-management.io-crds.yaml
  fleetconfig-controller/charts/fleetconfig-controller/templates/ocm/add-ons.yaml
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/config/crd/bases/fleetconfig.open-cluster-management.io_fleetconfigs.yaml
  fleetconfig-controller/go.mod
  fleetconfig-controller/internal/controller/addon.go
  fleetconfig-controller/internal/controller/hub.go
  fleetconfig-controller/internal/controller/spoke.go
  fleetconfig-controller/test/data/addon-2-cm.yaml
  fleetconfig-controller/test/data/fleetconfig-values.yaml
  fleetconfig-controller/test/e2e/fleetconfig.go
  fleetconfig-controller/test/e2e/helper.go
Labels: approved, lgtm

#37 🌱 enable manual releases via workflow dispatch
  .github/workflows/release.yml
  .github/workflows/releaseimage.yml
Labels: approved

#38 fix: only set addonconfigured condition when num addons > 0
  fleetconfig-controller/charts/fleetconfig-controller/README.md
  fleetconfig-controller/charts/fleetconfig-controller/values.yaml
  fleetconfig-controller/internal/controller/hub.go
Labels: approved, lgtm
